version: '3.1'

services:
  institute-mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "-u", "root", "-p", "example", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 10

  institute-mongosh:
    image: ghcr.io/agile-learning-institute/institute-mongosh:latest
    depends_on:
      institute-mongodb:
        condition: service_healthy
    environment:
      - HOST=institute-mongodb
      - USER=root
      - PASSWORD=example
      - AUTH_DB=admin
      - DB_NAME=agile-learning-institute
      - SCRIPT_PATH=/src/migrate.js
      - LOAD_TEST=true
    entrypoint: ["/src/entrypoint.sh"]



